media: assets/images

collections:
  - name: productos
    label: Productos
    folder: data/
    extension: json
    format: json
    create: true
    fields:
      - { name: id, label: ID, widget: number, required: false }
      
      - name: nombre
        label: Nombre
        widget: object
        fields:
          - { name: es, label: Español, widget: string }
          - { name: en, label: Inglés, widget: string }
      
      - name: descripcion
        label: Descripción
        widget: object
        fields:
          - { name: es, label: Español, widget: text }
          - { name: en, label: Inglés, widget: text }
      
      - { name: precio, label: Precio, widget: number }
      
      - name: categoria
        label: Categoría
        widget: select
        options:
          - { label: Camisas, value: camisas }
          - { label: Accesorios, value: accesorios }
          - { label: Pantalones, value: pantalones }
          - { label: Zapatos, value: zapatos }
          - { label: Faldas, value: faldas }
          - { label: Peluches, value: peluches }
          - { label: Maletas, value: maletas }
      
      - name: imagenes
        label: Imágenes
        widget: list
        fields:
          - { name: url, label: URL, widget: image }
      
      - { name: activo, label: Activo, widget: boolean, default: true }