media: assets/images

content:
  - name: productos
    label: Productos
    type: file
    path: data/productos.json
    format: json
    list: true
    
    fields:
      - name: id
        label: ID
        type: number
        required: false

      - name: nombre
        label: Nombre
        type: object
        fields:
          - name: es
            label: Español
            type: string

          - name: en
            label: Inglés
            type: string

      - name: descripcion
        label: Descripción
        type: object
        fields:
          - name: es
            label: Español
            type: text

          - name: en
            label: Inglés
            type: text

      - name: precio
        label: Precio
        type: number

      - name: categoria
        label: Categoría
        type: select
        options:
          values:
            - { label: "Camisas", value: "camisas" }
            - { label: "Accesorios", value: "accesorios" }
            - { label: "Pantalones", value: "pantalones" }
            - { label: "Zapatos", value: "zapatos" }
            - { label: "Faldas", value: "faldas" }
            - { label: "Peluches", value: "peluches" }
            - { label: "Maletas", value: "maletas" }

      - name: imagenes
        label: Imágenes
        type: image
        options:
          multiple: true
          max: 20

      - name: activo
        label: Activo
        type: boolean
        default: true
